//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIALGenieWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BookingDetail
    {
        public string GuestName { get; set; }
        public string PassportNumber { get; set; }
        public string ServiceOpted { get; set; }

        [DataType(DataType.Date)]
        public string DateBooked { get; set; }

        [DataType(DataType.Date)]
        public string DateOn { get; set; }

        [DataType(DataType.Time)]
        public string TimeAt { get; set; }
        public int id { get; set; }
        public string AmountPaid { get; set; }
        public string Status { get; set; }
    }
}

