//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIALGenieWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FlightDetail
    {
        public string FlightType { get; set; }
        public string ArrivalFlightNo { get; set; }
        public string ArrivalAirline { get; set; }

        [DataType(DataType.Date)]
        public string ArrivalDate { get; set; }

        [DataType(DataType.Time)]
        public string ArrivalTime { get; set; }
        public string Origin { get; set; }
        public string PNRNumber { get; set; }
        public int Id { get; set; }

        public string PassportNumber { get; set; }
    }
}
