//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIALGenieWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymServiceView
    {
        public string GuestName { get; set; }
        public string PassportNumber { get; set; }
        public string ServiceOpted { get; set; }
        public string DateBooked { get; set; }
        public string Emailid { get; set; }
        public string Mobile { get; set; }
        public string PreferredLanguage { get; set; }
        public string SpecialReq { get; set; }
        public string FlightType { get; set; }
        public string ArrivalFlightNo { get; set; }
        public string ArrivalAirline { get; set; }
        public string ArrivalDate { get; set; }
        public string ArrivalTime { get; set; }
        public string duration { get; set; }
        public string payment { get; set; }
        public string amount { get; set; }
        public string Origin { get; set; }
        public string PNRNumber { get; set; }
        public string Nationality { get; set; }
        public string Dob { get; set; }
    }
}
