//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIALGenieWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PassengerDetail
    {
        public string GuestName { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Emailid { get; set; }
        public string Mobile { get; set; }
        public string PreferredLanguage { get; set; }
        public string SpecialReq { get; set; }
        public int Id { get; set; }
        public string PassportNumber { get; set; }
        public string Nationality { get; set; }

        [DataType(DataType.Date)]
        public string Dob { get; set; }
    }
}