//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIALGenieWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spaservice
    {
        public int id { get; set; }
        public string PassportNumber { get; set; }
        public string GuestName { get; set; }
        public string duration { get; set; }
        public string therapist { get; set; }
        public string amount { get; set; }
        public string payment { get; set; }
    }
}
